services:
  app:
    image: ghcr.io/312022151125/go-backend-template:develop
    container_name: go-backend-template
    restart: unless-stopped
    ports:
      - "40000:8080"
    environment:
      GO_BACKEND_TEMPLATE_SERVER_HOST: "0.0.0.0"
      GO_BACKEND_TEMPLATE_SERVER_PORT: "8080"
    volumes:
      - ./data:/app/data